name: Deploy CloudFormation Stacks

# Controls when the action will run.
on:
  push:
    branches: [ master ]

jobs:

  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy-file to S3
        shell: bash
        env:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_s3_bucket: 'advance-use-case-dev'
        run: |
          sudo apt-get update && sudo apt-get -y install awscli
          aws configure set aws_access_key_id $aws_key_id
          aws configure set aws_secret_access_key $aws_secret_access_key 
          aws configure set default.region us-east-1
          result = aws cloudformation describe-stacks --stack-name s3-buckets
          echo $result
