name: Deploy CloudFormation Stacks

# Controls when the action will run.
on:
  push:
    branches: [ master ]

jobs:

  ValidateIFStackCreatedOrNot:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.output.test }}
    steps:
      - uses: actions/checkout@v2
      - name: Validate-Stack-Presence.
        shell: bash
        env:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_s3_bucket: 'advance-use-case-dev'
      - id: step1
        run: |
          sudo apt-get update && sudo apt-get -y install awscli
          aws configure set aws_access_key_id $aws_key_id
          aws configure set aws_secret_access_key $aws_secret_access_key 
          aws configure set default.region us-east-1
          result=`aws cloudformation describe-stacks --stack-name 's3-buckets' --query 'Stacks[0].StackStatus' --output text`
          echo "::set-output name=test::$result"
      - uses: actions/checkout@v2
      - name: Validate-result.
        shell: bash
      - id: step2
        run: |
          echo ${{ needs.outputs.output1 }}


